In [25]:
# import all libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import PolynomialFeatures
from sklearn.preprocessing import scale
from sklearn.feature_selection import RFE
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import make_pipeline
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

import warnings # supress warnings
warnings.filterwarnings('ignore')

In [38]:
?sklearn.metrics.accuracy_score

Object `sklearn.metrics.accuracy_score()` not found.

In [26]:
df = pd.read_csv("pima_indian_diabetes.csv")
dic = pd.read_csv("pima_indian_diabetes_data_dictionary.csv")
df.head()

,No_Times_Pregnant,Plasma_Glucose,Diastolic_BP,Triceps,Insulin,BMI,Age,Diabetes
0,1,89,66,23,94,28.1,21,0
1,0,137,40,35,168,43.1,33,1
2,3,78,50,32,88,31.0,26,1
3,2,197,70,45,543,30.5,53,1
4,1,189,60,23,846,30.1,59,1

In [27]:
dic

  No_Times_Pregnant                           Number of times pregnant
0    Plasma_Glucose  Plasma glucose concentration after 2 hours in ...
1      Diastolic_BP                   Diastolic blood pressure (mm Hg)
2           Triceps                   Triceps skin fold thickness (mm)
3           Insulin                     2-Hour serum insulin (mu U/ml)
4               BMI     Body mass index (weight in kg/(height in m)^2)
5               Age                                        Age (years)
6          Diabetes                            Class variable (0 or 1)

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 392 entries, 0 to 391
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   No_Times_Pregnant  392 non-null    int64
 1   Plasma_Glucose     392 non-null    int64
 2   Diastolic_BP       392 non-null    int64
 3   Triceps            392 non-null    int64
 4   Insulin            392 non-null    int64
 5   BMI                392 non-null    float64
 6   Age                392 non-null    int64
 7   Diabetes           392 non-null    int64
dtypes: float64(1), int64(7)
memory usage: 24.6 KB

In [29]:
df1 = df[['No_Times_Pregnant', 'Plasma_Glucose', 'Diastolic_BP', 'Triceps','Insulin', 'BMI', 'Age']]

In [30]:
df1 = (df-df.mean())/df.std()

In [31]:
df1.describe()

,No_Times_Pregnant,Plasma_Glucose,Diastolic_BP,Triceps,Insulin,BMI,Age,Diabetes
count,3.920000e+02,3.920000e+02,3.920000e+02,3.920000e+02,3.920000e+02,3.920000e+02,3.920000e+02,3.920000e+02
mean,-9.063045e-18,1.132881e-17,-4.690126e-16,9.289621e-17,1.314142e-16,1.472745e-16,1.155538e-16,9.969350e-17
std,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
min,-1.027899e+00,-2.158972e+00,-3.734229e+00,-2.105793e+00,-1.195339e+00,-2.118234e+00,-9.670632e-01,-7.035037e-01
25%,-7.165108e-01,-7.656174e-01,-6.932780e-01,-7.745416e-01,-6.673258e-01,-6.668258e-01,-7.709997e-01,-7.035037e-01
50%,-4.051225e-01,-1.175457e-01,-5.307782e-02,-1.382677e-02,-2.571162e-01,1.618967e-02,-3.788727e-01,-7.035037e-01
75%,5.290424e-01,6.601404e-01,5.871224e-01,7.468881e-01,2.856226e-01,5.711397e-01,5.034131e-01,1.417831e+00
max,4.265702e+00,2.442338e+00,3.147923e+00,3.219211e+00,5.805571e+00,4.839986e+00,4.914842e+00,1.417831e+00

In [32]:
# Putting feature variable to X
X = df.drop(['Diabetes'],axis=1)

# Putting response variable to y
y = df['Diabetes']

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.7, test_size=0.3, random_state=100)